base: https://1k.any.digital
title: 1000 Goals Tracker
brand: 1⚽️⚽️⚽️ <sup class="brand">Goals<br>Tracker</sup>
header_links:
  - url: https://github.com/anyblades/1k.any.digital
    title: <i class="fa-solid fa-laptop-code fa-sm faded"></i>
footer_contents:
  - |-
    Fully [open-source](//github.com/anyblades/1k.any.digital) tracker
    powered by [Blades CSS](https://blades.ninja/) using [11ty](//11ty.blades.ninja/).

    Content licensed [CC BY-SA 4.0](//github.com/anyblades/1k.any.digital/blob/main/content/LICENSE.md)
    © 2026 [Anydigital](https://any.digital/)
head_extras:
  - |-
    <style>
      sup.brand {
        display: inline-block; line-height: 1; top: 0;
        text-transform: uppercase; font-size: 45%;
      }
      body > footer { text-align: center }
    </style>
